### ISSUE TITLE
Set culture based off URL domain/tld instead of URL path

### ISSUE THREAD

**Issue by morgrowe** [LazZiya/ExpressLocalization#10]
Let's say I want to support to support two cultures: English and Welsh (Cymru).

I have a domain setup called mywebsite.wales and another one called mywebsite.cymru. Their DNS settings both point to the same server. Is it possible to configure ExpressLocalization to set the current culture based off the domain name?

Cheers
Morgan

**Comment by LazZiya** [comment]
Technically it is possible, you can create a [custom culture provider][1] that reads the domain name and set the culture accordingly. 

e.g. create DomainCultureProvider:

````cs
// not tested, just for demonstration:)
public class DomainCultureProvider : IRequestCultureProvider
{
    public Task<ProviderCultureResult> DetermineProviderCultureResult(HttpContext httpContext)
    {
        // This will get the domain name as string vale
        var domain = httpContext.Request.Host.Value;

        if (domain == "mywebsite.wales")
        {
            return Task.FromResult(new ProviderCultureResult("en"));
        }
        else
        {
            return Task.FromResult(new ProviderCultureResult("cy"));
        }
    }
}
````

Then insert it to at the zero position in the culture providers list in startup file:

````cs
services.AddMvc()
    .AddExpressLocalization<ExpressLocalizationResource, ViewLocalizationResource>(ops =>
    {
        ops.ResourcesPath = "LocalizationResources";
        ops.RequestLocalizationOptions = o =>
        {
            o.SupportedCultures = cultures;
            o.SupportedUICultures = cultures;
            o.DefaultRequestCulture = new RequestCulture("en");
            o.RequestCultureProviders.Insert(0, new DomainCultureProvider());
        };
    })
````

If it didn't work, you may need to insert the DomainCultureProvider after doing the expresslocalization setup, so you can make sure it is at zero position.

[1]:https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization-extensibility?view=aspnetcore-3.0#use-customrequestcultureprovider

**Comment by morgrowe** [comment]
This makes perfect sense and I'll give it a go early next week. Thank you!

Cheers
Morgan

**Comment by LazZiya** [comment]
Issue will be closed, hopefully the provided solution solved your problem,

if you need any further help re this topics feel free to re-open the issue,

kind regards,
Ziya
