### ISSUE TITLE
Null pointer exception

### ISSUE THREAD

**Issue by myusernamedm** [LazZiya/ExpressLocalization#19]
[github.com/LazZiya/ExpressLocalization/wiki/One-Resource-File](url)

I have created the LocSource.cs file in my LocalizationResources folder and added the code below to the Startup.cs file.

I am getting a null pointer exception in the browser when I start the app. 

`services.AddRazorPages() .AddExpressLocalization<LocSource>(ops => { /* options */ }); `

Thanks.

**Comment by LazZiya** [comment]
Hi @myusernamedm 

Have you defined the options? somehow I feel that you could be used the code as mentioned with the `/* options */` and not defined the `options` 🤔 

````cs
services.AddRazorPages()
        .AddExpressLocalization<LocSource>(
            ops =>
            {
                ops.ResourcesPath = "LocalizationResources";
                ops.RequestLocalizationOptions = o =>
                {
                    o.SupportedCultures = cultures;
                    o.SupportedUICultures = cultures;
                    o.DefaultRequestCulture = new RequestCulture("en");
                };
            });
````

The code there is only to demonstrate the differentiated setup for resource files, so it dosen't show the options, but in real life the options must be defined :)

**Comment by myusernamedm** [comment]
You're right, I hadn't changed my options from my original attempt (ExpressLocalizationResource.de.resx) to point to my LocSource.de.resx resource file.

Null pointer exception is gone. But still stuck with my original problem - the label on-screen is not changing when I select a different language from the dropdown. There is a connection or plumbing missing somewhere.

I'm wondering if maybe there was a change in V4.0.0 that is causing the dropdown to not use the resx values correctly?

**Comment by LazZiya** [comment]
Can you share your repo? so I can check what is missing...
Or you may see [these sample repos](https://github.com/lazziya/expressLocalizationsamplecore3) and compare with your code.

**Comment by myusernamedm** [comment]
I got it! :)

My resx file had its Build Action property as 'Content' instead of 'Embedded Resource'.
And my LocSource.cs had its Build Action property as 'Embedded Resource' instead of 'C# compiler'.

Really looking forward to using this package now, looks like it will make life much easier. Also thank you very much for the help & feedback.

Stay safe.

**Comment by LazZiya** [comment]
glad for help :)
