### ISSUE TITLE
Change culture along with Area and extra parameter

### ISSUE THREAD

**Issue by faresayyad** [LazZiya/ExpressLocalization#20]
Hello, 

I am facing a strange issue when trying to change the culture when I am on the following page: 
http://localhost:xxxxx/en/Admin/GlobalSettings/Edit?Id=1
where: 
1- Admin is an area.
2- GlobalSettings is a controller. 
3- Edit is an action
4- is a parameter.
** Note: this page is working perfectly when I navigate from the index page by passing these tag helpers to the tag:
` <a asp-action="Edit" asp-area="Admin" asp-route-culture="@CultureInfo.CurrentCulture.Name" asp-route-Id="1" class="btn btn-primary btn-modern"><localize>Update</localize></a>`

but when I try to change the culture when I am on this page it gave me the following
No webpage was found for the web address: http://localhost:xxxxx/en/GlobalSettings?area=Admin
HTTP ERROR 404

In _Layout:
@{var routeData = ViewContext.RouteData.Values;
    routeData["culture"] = "{0}"; }
 <language-nav redirect-to-url="@(Url.RouteUrl(routeData)) "></language-nav>

**Comment by LazZiya** [comment]
Hi @faresayyad ,

Can you please provide more details:
- Version of `ExpressLocalization`
- Registered routes
- How do you change the culture? are you using [LanguageNavTagHelper](https://github.com/LazZiya/TagHelpers/wiki/LanguageNav-TagHelper-Setup#redirect-to-url)
- Can you explain how do you use the code in `_Layout`?
````html
routeData["culture"] = "{0}"; //how do you use this?
````

**Comment by faresayyad** [comment]
@LazZiya 
Thank you for quick response, 
Yes, sure: 
the app is developed on top of .net core 3.1 
1- version is: LazZiya.ExpressLocalization 4.0.0
2- in startup.cs  I use endpoints to configure routes:
```



 app.UseEndpoints(endpoints =>
            {
                endpoints.MapAreaControllerRoute(
                               name: "Admin",
                               "Areas",
                               pattern: "{culture=en}/{area:exists}/{controller=GlobalSettings}/{action}/{id?}");

                endpoints.MapControllerRoute(
                    name: "default",
                    pattern: "{culture=en}/{controller=Home}/{action=Index}/{id?}");

                endpoints.MapControllers();
                endpoints.MapRazorPages();
            });
```

** one for areas and the other for default 

3- Yes I change the culture using LanguageNavTagHelper, as you mentioned here: 
https://github.com/LazZiya/TagHelpers/wiki/LanguageNav-TagHelper-Setup#redirect-to-url
```
@{ 
    var routeData = ViewContext.RouteData.Values;
    routeData["culture"] = "{0}";
}
<language-nav redirect-to-url="@(Url.RouteUrl(routeData))"></language-nav>
```


![2020-05-14_13-14-52](https://user-images.githubusercontent.com/11721949/81922860-67d0ad80-95e5-11ea-9640-2e0efd3c5aca.gif)

These are the helpers passed to anchor tag: 
<a asp-action="Edit" asp-area="Admin" asp-route-culture="@CultureInfo.CurrentCulture.Name" asp-route-Id="1" class="btn btn-primary btn-modern"><localize>Update</localize></a>

**Comment by LazZiya** [comment]
@faresayyad Looks like you need the routing attributes on the controller:

````cs
[Area("Admin")]
[Route("{culture=en}/Admin/[controller]/[action]")]
public class GlobalSettingsController : Controller
{
    // ...
}
````

----

Additional notices:

- Instead of this:
````html
<a href="..."><localize>Update</localize></a>
````
You can do this:
````html
<a href="..." localize-content>Update</a>
````

- Make sure that `routeData` is defined directly above the `<language-nav>` tag, otherwise VS will fail to compile the project but will not show an error in the Error List!

**Comment by LazZiya** [comment]
@faresayyad I hope that the previous reply has answered your question and solved your problem.

I will close this issue, and feel free to reopen if you need any further help,

Regards,
Ziya

**Comment by faresayyad** [comment]
Thank you very much, yes this issue was solved 
and sorry for late response

**Comment by faresayyad** [comment]
Hello, 

I would like to reopen the question, please.
One of the cases I faced regarding parameters is like this:
```

   [Route("{culture}/Properties/Details/{propRefNo?}")]
        public async Task<IActionResult> PropertyDetails(string propRefNo)
```

as you can see the parameter is of type string. whenever I try to change the language the parameters are gone. 
Please refer to the below image marked with red.
![image](https://user-images.githubusercontent.com/11721949/130336230-99a00420-7c99-4250-8203-ddae874ebdd3.png)
@LazZiya
