### ISSUE TITLE
NullReferenceException when RazorPages is not enabled for MVC project with .NET CORE 3.1

### ISSUE THREAD

**Issue by mmsaffari** [LazZiya/ExpressLocalization#22]
`services.AddExpressLocalization<>()` throws a `NullReferenceException` when called in a Startup.cs of an MVC project with .NET Core 3.1.
The exception can be traced back to `ExAddRouteValueRequestCultureProvider()` under `LazZiya.ExpressLocalization.ExpressLocalizationExtensions`.  

I'll send a PR to change  

    builder.AddRazorPagesOptions(x =>
    {
        x.Conventions.Add(new RouteTemplateModelConvention());
    });

into

    builder.AddRazorPagesOptions(x =>
    {
        if (x.Conventions != null)
        {
            x.Conventions.Add(new RouteTemplateModelConvention());
        }
    });

**Comment by LazZiya** [comment]
Thanks @mmsaffari for reporting this issue, I tried to reproduce it but I didn't get any exception.

Can you please share the steps/startup settings you did to see the exception?

**Comment by mmsaffari** [comment]
Hello Ziya :)
When creating an MVC project, if "enable Razor runtime compilation" is checked, but `services.AddRazorPages();` is not included in the `ConfigureServices(IServiceCollection services)`, the exception will be thrown.

![Annotation 2020-05-19 150211](https://user-images.githubusercontent.com/954277/82316623-53742280-99e2-11ea-9254-ae52b9da6ce6.png)


PS: A normal MVC project (without that feature enabled) does not throw this exception, exactly as you have mentioned.

**Comment by LazZiya** [comment]
@mmsaffari thanks for the details, just confirmed the issue.

With reference to your offered solution I managed to solve it with null checker :)
````cs
x.Conventions?.Add(new RouteTemplateModelConvention());
````
I'll do my tests to check if there is any undesired behavior with this solution bedore publishing the fix.
