### ISSUE TITLE
Missing ExRequiredAttributeAdapter

### ISSUE THREAD

**Issue by kliszaq** [LazZiya/ExpressLocalization#24]
Hi,
nice work with the library.
I think you've missed the ExRequiredAttributeAdapter that could be easy written as there is already base code available: https://github.com/aspnet/Mvc/blob/master/src/Microsoft.AspNetCore.Mvc.DataAnnotations/RequiredAttributeAdapter.cs

I checked the ExpressValidationAttributeAdapterProvider and it seems that it uses the base RequiredAttributeAdapter. In my case this adapter does not emit the data-val-* atrributes on the client side.

cheers,
Kamil

**Comment by kliszaq** [comment]
Ok, after having closer look on that I found that when you want to implement your own IValidationAttributeAdapterProvider implementation then localized one is not taken into account. Therefore validation disappears.
I solved this issue with a trick - I wrapped localized adapter provider into a singleton wrapper class and then redefined my won implementation to fallback with the wrapper if my attribute was not found. The most challenging thing was to resolve current localized implementation in the ConfigureServices section:

```
 public static void ConfigureValidation(this IServiceCollection services)
        {
            var serviceProvider = services.BuildServiceProvider();
            var localizedServiceProvider = serviceProvider.GetRequiredService<IValidationAttributeAdapterProvider>();
            services.AddSingleton(new ValidationAttributeAdapterProviderWrapper(localizedServiceProvider));
            services.AddSingleton<IValidationAttributeAdapterProvider, CustomValidationAttributeAdapterProvider>();
        }
```

and

```
    public class ValidationAttributeAdapterProviderWrapper : IValidationAttributeAdapterProvider
    {
        private readonly IValidationAttributeAdapterProvider _adapterProvider;

        public ValidationAttributeAdapterProviderWrapper(IValidationAttributeAdapterProvider adapterProvider)
        {
            _adapterProvider = adapterProvider;
        }

        public IAttributeAdapter GetAttributeAdapter(ValidationAttribute attribute, IStringLocalizer stringLocalizer)
        {
            return _adapterProvider.GetAttributeAdapter(attribute, stringLocalizer);
        }
    }
```

then my validator adapter works with the localized version:
```
 public class CustomValidationAttributeAdapterProvider : IValidationAttributeAdapterProvider
    {
        private readonly ValidationAttributeAdapterProviderWrapper _adapterProviderWrapper;

        public CustomValidationAttributeAdapterProvider(ValidationAttributeAdapterProviderWrapper adapterProviderWrapper)
        {
            _adapterProviderWrapper = adapterProviderWrapper;
        }

        public IAttributeAdapter GetAttributeAdapter(ValidationAttribute attribute, IStringLocalizer stringLocalizer)
        {
            if (attribute is MyValidatorAttribute)
            {
                return new MyValidatorAttributeAdapter(attribute as MyValidatorAttribute, stringLocalizer);
            }

            return _adapterProviderWrapper.GetAttributeAdapter(attribute, stringLocalizer);
        }
    }
```

I hope it can help someone with this issue. 
Or it would be the best if there would be more convinient way to handle that.

**Comment by LazZiya** [comment]
Hi @kliszaq and thanks for your posts,

Actually it is not missed :) simply the [`[ExRequired]`](https://github.com/LazZiya/ExpressLocalization/wiki/DataAnnotations-Localization-Using-Express-Attributes) can produce the localized message with the default `RequiredAttributeAdapter`. 

Can you please give me more detail/steps to reproduce your issue with `data-val-*` on client side?

**Comment by LazZiya** [comment]
Closing issue due to long time inactivity.
Feel free to reopen if you still need help.

Best,
Ziya
