### ISSUE TITLE
Retrieve Value from .resx file

### ISSUE THREAD

**Issue by myusernamedm** [LazZiya/ExpressLocalization#27]
Is it possible to retrieve a value from one of your localization.resx files using the primary key - directly from a C# class?

I have been trying to do this, so I can unit test the value, but because the Express Localization file structure embeds the .resx file under the LocSource.cs file I cant seem to retrieve values directly. If this is possible, it might be useful for other people also to add it to your documentation. I looked but cant find it there, apologies if I missed it. Thanks.

**Comment by LazZiya** [comment]
Hi @myusernamedm ,

If I understood the question right, you can inject `ISharedCultureLocalizer` to the class and retrive a localized value as below:
````csharp
public class Foo
{
    private readonly ISharedCultureLocalizer _localizer;

    public Foo(ISharedCultureLocalizer localizer)
    {
        _localizer = localizer ?? throw new NotImplementedException(nameof(localizer));
    }

    public string Test(string key)
    {
        return _localizer[key]
    }
}
````

btw, if you are in an early phase of developing a new app, I suggest to have a look at my new package **[`XLocalizer`](https://github.com/LazZiya/XLocalizer)**, it offers online translation and auto saving localized keys to db or xml and much more, see the [docs](http://docs.ziyad.info/XLocalizer) for more details :)

**Comment by myusernamedm** [comment]
Hi,
Thanks for the reply, I am planning to try implementing this today.
Apologies for the delay.

I would be happy to try out XLocalizer, but probably a bit too far down the road with my current app. Will have a look at it shortly. Thanks again.

**Comment by LazZiya** [comment]
You are welcome @myusernamedm ,
Feel free to reopen the issue if you still need help

best,
Ziya

**Comment by myusernamedm** [comment]
Hi,

I am having still trouble with the injection, but I don't think its an Express Localization issue, it might be an xunit dependency issue. Would you have any ideas?

**The following constructor parameters did not have matching fixture data: ISharedCultureLocalizer localizer**

```
    public class TestAboutPageLocSourceNames
    {
        public readonly ISharedCultureLocalizer _localizer;

        public TestAboutPageLocSourceNames(ISharedCultureLocalizer localizer)
        {
            _localizer = localizer ?? throw new NotImplementedException(nameof(localizer));
        }

        public string Test(string key)
        {
            return _localizer[key];
        }

        [Fact]
        [Trait("Category", "Unit")]
        [Trait("Owner", "DM")]
        [Trait("RunTime", "Short")]
        public void LocSourcePageTabTitleNameReferenceForAboutPageIsCorrect()
        {
            string LocSourcePageTabTitle = Test("About Us");
            var AboutPageLocSourceNamesLibrary = new AboutPageLocSourceNames();
            string ReturnedNameKeyValue = AboutPageLocSourceNamesLibrary.GetLocSourcePageTabTitleNameReferenceForAboutPage();
            Assert.Equal(LocSourcePageTabTitle, ReturnedNameKeyValue);
        }
```

I have tried injecting the IClassFixture to my test class, but this doesn't help.

`    public class TestAboutPageLocSourceNames : IClassFixture<ISharedCultureLocalizer>`

**Comment by LazZiya** [comment]
Sorry for the delay, I was a bit busy with other projects.

I've created a sample to test `ISharedCultureLocalizer` with real data from resx file, hope this helps :)

````cs
public class UnitTest1
{
    private readonly ISharedCultureLocalizer _loc;

    public UnitTest1()
    {
        var locOps = Options.Create(new LocalizationOptions { ResourcesPath = "LocalizationResources" });

        var sfactory = new ResourceManagerStringLocalizerFactory(locOps, NullLoggerFactory.Instance);
        var hfactory = new HtmlLocalizerFactory(sfactory);

        _loc = new SharedCultureLocalizer(hfactory, typeof(LocSource));
    }

    [Fact]
    public void Test1()
    {
        var str = _loc.GetLocalizedString("tr", "Welcome", null);

        Assert.True(str == "Merhaba");
    }
}
````

**Comment by myusernamedm** [comment]
Brilliant! Its working now, thanks a million, much appreciated!
