### ISSUE TITLE
Problem with ExpressValidationAttributeAdapterProvider

### ISSUE THREAD

**Issue by Gaudico** [LazZiya/ExpressLocalization#29]
I need to create custom DataAnnotations to work both on client side and server side.
I have tried to implement them as indicated in the Microsoft docs:
https://docs.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-3.1#custom-attributes
https://docs.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-3.1#client-side-validation

But when adding my own provider in dependency injection, I have overwritten the one used by this system and the 'Ex' DataAnnotations (ExRequiredAttribute, etc) on the client side have stopped working (no longer painting the _data-val-*_ attributes in the inputs).

The problem is that the operation of ExpressValidationAttributeAdapterProvider cannot be extended since it is internal, and neither can you create your own provider since you cannot add the adapters of the "Ex" DataAnnotations because they are also internal.

How can I add new adapters for custom validation attributes without affecting the "Ex" DataAnnotations functionality?

**Comment by Gaudico** [comment]
As a workaround I have created this Adapter injected as singleton and it seems to work fine:
```
    public class CustomValidationAttributeAdapterProvider : IValidationAttributeAdapterProvider
    {
        private IValidationAttributeAdapterProvider _baseProvider;
        private IValidationAttributeAdapterProvider BaseProvider
        {
            get
            {
                if (_baseProvider != null)
                    return _baseProvider;

                var providers = _services.GetServices<IValidationAttributeAdapterProvider>();

                _baseProvider = providers.FirstOrDefault(i => i.GetType().Name.StartsWith("ExpressValidationAttributeAdapterProvider"))
                                ?? new ValidationAttributeAdapterProvider();
                return _baseProvider;
            }
        }
        private readonly IServiceProvider _services;


        public CustomValidationAttributeAdapterProvider(IServiceProvider services)
        {
            _services = services;
        }
        
        public IAttributeAdapter GetAttributeAdapter(ValidationAttribute attribute, IStringLocalizer stringLocalizer)
        {
            return attribute switch
            {
                RequireAtLeastOneOfGroupAttribute requireAtLeastOneOfGroupAttribute => new RequireAtLeastOneOfGroupAttributeAdapter(requireAtLeastOneOfGroupAttribute , stringLocalizer),
                _ => BaseProvider.GetAttributeAdapter(attribute, stringLocalizer)
            };
        }
    }
```

**Comment by LazZiya** [comment]
## Option 1 : 
In startup file set `UseExpressValidationAttributes` to false:
````cs
services.AddRazorPages()
        .AddExpressLocalization<LocSource>(ops =>
        {
            ops.UseExpressValidationAttributes = false;
            // ...
        });
````
This will not register `ExpressValidationAttributeAdapterProvider`, so you will be able to create your own custom adapter, then register it and configure data annotation localization. 

To do so, you can create an extension method as below:

````cs
/// <summary>
/// </summary>
/// <typeparam name="T">Type of localization resource</typeparam>
public static IMvcBuilder AddCustomDataAnnotationsLocalization<T>(this IMvcBuilder builder) where T : class
{
    builder.AddDataAnnotationsLocalization(ops =>
    {
        var t = typeof(T);
        ops.DataAnnotationLocalizerProvider = (type, factory) =>
            factory.Create(t.Name, t.Assembly.GetName().Name);
    });
    
    builder.Services.AddSingleton<IValidationAttributeAdapterProvider, CustomValidationAttributeAdapterProvider>();

    return builder;
}
````
Then you can simply call it from startup:

````cs
services.AddRazorPages()
         .AddExpressLocalization<LocSource>(ops =>
         {
             ops.UseExpressValidationAttributes = false;
             // ...
        })
        .AddCustomDataAnnotationsLocalization<LocSource>();
````
 
To keep using ExAttributes make sure that your have configured them as in [`ExpressValdiationAttributeAdapterProvider`](https://github.com/LazZiya/ExpressLocalization/blob/master/LazZiya.ExpressLocalization/DataAnnotations/ExpressValidationAttributeAdapterProvider.cs).

## Option 2 :
Just saw your newly posted answer :)

## Option 3 :
I've developed a [newer localization project](https://github.com/LazZiya/XLocalizer/) with much more powerful features (auto resource creating, online translation, etc.) and the [valdiation attributes provider](https://github.com/LazZiya/XLocalizer/blob/master/XLocalizer/DataAnnotations/ExpressValidationAttributeAdapterProvider.cs) is configured as public class, that may give you more options to configure.

**Comment by LazZiya** [comment]
@Gaudico, I think you are right since all Ex AttributeAdapters are internal classes! if converting them to public can solve your problem, I can publish a hotfix soon. is it okay?

**Comment by Gaudico** [comment]
Yes, but for it to work, I would have to copy the implementation of IValidationAttributeAdapterProvider.GetAttributeAdapter made for ExpressValdiationAttributeAdapterProvider into my provider.
Maybe the best solution will be to take that piece of code to some public place with which I can invoke from my own adapter, so if in the future this implementation changes, I would not have to worry about updating the adapter code.

However, I am very interested in your new project and I will take a look at it and see if I switch to that system.
Thank you very much for responding so quickly, and excuse my English, it is not my native language and I asked Google for a little help :)

**Comment by LazZiya** [comment]
Just published the hotfix for your issue,

* First install the latest version 4.0.2
* I've introduced a new class [`ExAttributeSwitch`](https://github.com/LazZiya/ExpressLocalization/blob/master/LazZiya.ExpressLocalization/DataAnnotations/ExAttributeSwitch.cs) and moved all the code required for selecting an Ex attribute adapter to a static method that you can call from within your own adapter:

````cs
public IAttributeAdapter GetAttributeAdapter(ValidationAttribute attribute, IStringLocalizer stringLocalizer)
{
    return ExAttributeSwitch.GetAttributeAdapter<T>(attribute, stringLocalizer) ?? base.GetAttributeAdapter(attribute, stringLocalizer);
}
````
So, you can continue with **Option 1** in my previous reply.

Feel free to ask me if you need any further help.

> English is not my native language as well :) 

BR,
Ziya

**Comment by Gaudico** [comment]
It works like a charm, thank you very much.

I really like what I have seen of your new project so I will surely move to that system. Which leads me to the fact that this arrangement we've made is not going to be used for too long... hahaha.

**Comment by LazZiya** [comment]
glad to know it worked fine.

btw, this arrangement will not go for nothing, I will use it to improve the new system as well :)
