### ISSUE TITLE
ExRange unexpected behavior as Required

### ISSUE THREAD

**Issue by rrtischler** [LazZiya/ExpressLocalization#30]
I just changed the .net attributes to the Ex ones and got the fields with ExRange validating as if they were Required as well. 
I think it's because of this: 
https://github.com/LazZiya/ExpressLocalization/blob/05541bd5c5259fc9335d54e1eea34909fe2d5447/LazZiya.ExpressLocalization/DataAnnotations/Adapters/ExRangeAttributeAdapter.cs#L44

In my opinion the ExRange shouldn't validate as required.
For example, I'm using to validate a nullable number. If I needed to validate as required, I'd include that attribute as well.

Is there a workaround for the ExRange that doesn't validate as required?

For now, I'm using as below, but I would rather use ExRange or other way that doesn't need to set the ErrorMessage every time.
`[Range(1, 999999, ErrorMessage = DataAnnotationsErrorMessages.RangeAttribute_ValidationError)]`

Thanks!

**Comment by LazZiya** [comment]
Hi @rrtischler, 

You are right, just checked the source code of [`RangeAttributeAdapter`][1] and found that it has no required validation!

I will publish a hotfix soon :)

[1]:https://source.dot.net/#Microsoft.AspNetCore.Mvc.DataAnnotations/RangeAttributeAdapter.cs,1f068e3acd767963

**Comment by LazZiya** [comment]
please use the [`updated package v4.0.3`](https://www.nuget.org/packages/LazZiya.ExpressLocalization/4.0.3) available at nuget.

Kind regards,
Ziya

**Comment by rrtischler** [comment]
It's working as intended now!

Thanks, @LazZiya !
