### ISSUE TITLE
ExpressLocalizationCore3 Field Validation Issue

### ISSUE THREAD

**Issue by myusernamedm** [LazZiya/ExpressLocalization#32]
Hi, I'm running into a strange defect with the implementation of ExpressLocalizationCore3. I have spent hours cross-checking against the sample application for Core3 and also against other pages I have working ok, but I cannot figure out what's going on here.

When My NewEmail field is empty the validation does not work, but when it has an invalid entry it does work.

**Empty Field validation text is not translated other than the embedded string for "New email" (This should be German):**

![EmptyFieldValidation](https://user-images.githubusercontent.com/39332143/111918175-c6737d00-8a7b-11eb-9fff-7ba7be9091d2.jpg)

**Invalid Field validation text is translated (This is Ok):**
![InvalidFieldValidation](https://user-images.githubusercontent.com/39332143/111918205-eb67f000-8a7b-11eb-83df-828b37e1f844.jpg)

**Input Model:
![InputModel](https://user-images.githubusercontent.com/39332143/111918234-0a668200-8a7c-11eb-9549-c349d9d13abf.jpg)
**

**LocSource.de.resx file**
![LocSourcederesx](https://user-images.githubusercontent.com/39332143/111918240-15211700-8a7c-11eb-833d-821cde8b381b.jpg)
![image](https://user-images.githubusercontent.com/39332143/111918255-25d18d00-8a7c-11eb-9275-fe84bb4bc25a.png)

**cshtml:**
![html](https://user-images.githubusercontent.com/39332143/111918271-397cf380-8a7c-11eb-85ee-e788092a7960.jpg)

Any pointers would be much appreciated?

**Comment by LazZiya** [comment]
Hi @myusernamedm ,

just use `[ExRequired]` instead of `[Required]`.

The reason why is explained in the docs :) for more details see [Express Validation Attributes](https://docs.ziyad.info/en/LazZiya.ExpressLocalization/v4.0/DataAnnotations-Localization-Using-Express-Attributes.md).

**Comment by myusernamedm** [comment]
Thank you!
