### ISSUE TITLE
Breaking change in MS.NET.Test.Sdk

### ISSUE THREAD

**Issue by myusernamedm** [LazZiya/ExpressLocalization#37]
Hi,

I updated the Microsoft.NET.Test.Sdk package from 16.11.0 to 17.0.0 and when I run my unit tests they fail with the error:

`System.InvalidOperationException : Different CurrentCulture and CurrentUICulture culture is not supported.`

I reverted the package and they run fine.

For info.

**Comment by LazZiya** [comment]
Hi @myusernamedm 

Thank you for reporting this issue, I will check and provide a fix next month.

Best,
Ziya

**Comment by LazZiya** [comment]
Hi @myusernamedm 

Just had the time to look for the issue. The [`CultureSwitcher`](https://github.com/LazZiya/ExpressLocalization/blob/master/LazZiya.ExpressLocalization/CultureSwitcher.cs) in `ExpressLocalization` requires both `CultureInfo.CurrentCulture` and `CultureInfo.CurrentUICulture` to be the same. It seems that the test project is using different values e.g. 
````cs
// This will give error
CultureInfo.CurrentCulture = "en"
CultureInfo.CurrentCulture = "en-US"
````

Can you try to set both values to be identical?

Best,
Ziya

**Comment by myusernamedm** [comment]
Hi,

Sorry for the delay, I was away for a while.

Where can I find the CultureSwitcher? I have searched my solution and cannot find where these values are set.

In my Startup ConfigureServices I have:
```
            var cultures = new[]
            {
                new CultureInfo("de"),
                new CultureInfo("en"),
            };

            services.AddMvc()
    .AddExpressLocalization<LocSource>(ops =>
    {
        ops.UseAllCultureProviders = false;
        ops.ResourcesPath = "LocalizationResources";
        ops.RequestLocalizationOptions = o =>
        {
            o.SupportedCultures = cultures;
            o.SupportedUICultures = cultures;
            o.DefaultRequestCulture = new RequestCulture("en");
        };
    });
```

**Comment by LazZiya** [comment]
Welcome back @myusernamedm :)

`CultureSwitcher` is used internally by `ExpressLocalization` to change the language, in general you don't need to use it manually, except for special use cases.

 Nothing wrong in your localization settings! It seems that the new SDK is providing different values for `CurrentCulture` and `CurrentUICulture` so the exception is thrown. 

Can you make sure to provide same value manually in your test environment for both values?

**Comment by myusernamedm** [comment]
Thanks, I've done a bit of digging based off your reply and it seems that's exactly the issue and the solution. For now I'm going to continue using the old SDK and I'll reach out to Microsoft to see if they intend to revert this in a future release as it seems like a breaking change in the SDK update.
