### ISSUE TITLE
Tested idea. Do not block others сulture providers

### ISSUE THREAD

**Issue by InfDev** [LazZiya/ExpressLocalization#4]
For other providers to work when a segment is not defined, it would be nice to replace the return 
  Task.FromResult(new ProviderCultureResult(DefaultCulture)) 
on 
  Task.FromResult&lt;ProviderCultureResult&gt;(null)
in the DetermineProviderCultureResult method of RouteValueRequestCultureProvider class.

Thus, the problem of using the current culture from cookies on pages where a culture segment cannot be applied, for example, in the extensions: HangFire Dashboard, SignalR hubs and others.

The name RouteSegmentCultureProvider more accurate than RouteValueRequestCultureProvider

**Comment by LazZiya** [comment]
@InfDev thanks for the idea, I was updating the package to support DotNet Core 3.0 so I didn't really had the time to review it, but I will consider your suggest ın the next update :)

**Comment by LazZiya** [comment]
Hi @InfDev , just release the new version with your helpful suggestion 👍 
https://github.com/LazZiya/ExpressLocalization/releases/tag/v3.1.2
