### ISSUE TITLE
Always Redirect to default culture or user's previously selected culture

### ISSUE THREAD

**Issue by dnnbuddy** [LazZiya/ExpressLocalization#8]
Hi,

How can we redirect to default culture if it is not specified in the url?

At the same time, how can we auto redirect to user's previously selected culture value (we can get culture value from a cookie)?

Thanks.

**Comment by LazZiya** [comment]
Hi,

The default culture is specified during the setup in startup, below is a simplified implementation:

````cs
services.AddMvc()
    .AddExpressLocalization<SharedResourceType>(ops =>
    {
        ops.RequestLocalizationOptions = o =>
        {
            // ...

            // Set the default culture here
            o.DefaultRequestCulture = new RequestCulture("en"); 
        };
    });
````

Re redirecting to a previously selected culture, currently the redirecting works only with the default culture, but I see your suggestion as a nice to have new feature, will add it to the backlog hopefully I will find a time to implement it in next version.

**Comment by LazZiya** [comment]
Just revised the culture fallback behavior, unfortunately falling back to the previously selected culture is not a common practice, so it will not be implemented. See [Culture Fallback Behaviour](https://github.com/LazZiya/ExpressLocalization#culture-fallback-behaviour) for more details.

But you are free to fork and implement your own culture fallback behavior :)
